@startuml

left to right direction

actor Usuario
actor Prestador
actor Financeiro

rectangle :OPE: {
	Usuario -- (Cria ordem de serviço)
	Usuario -- (Envia ordem de serviço)
	Prestador -- (Continuidade ordem serviço)
	Prestador -- (Finaliza ordem de serviço)
	Usuario -- (Usuário retira peças)
	Usuario -- (Realiza baixa na OPE)
	Financeiro -- (Realiza pagamento)

(Envia ordem de serviço) .> (Continuidade ordem serviço) : include
(Finaliza ordem de serviço) .> (Usuário retira peças) : include
(Realiza baixa na OPE) .> (Realiza pagamento) : include
}

@enduml